### ISSUE TITLE
Error resolving dependencies in react native 0.20

### ISSUE THREAD

**Issue by L3V147H4N** [aakashns/react-native-dialogs#17]
I'm not sure if I'm putting things in the right places but since the new releases of react native project structure and files changed a little bit and I get the following error:

```
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-dialogs'.
   > Could not resolve all dependencies for configuration ':react-native-dialogs:_debugCompile'.
      > Could not find com.android.support:appcompat-v7:23.1.
        Searched in the following locations:
            https://jitpack.io/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom
            https://jitpack.io/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.jar
            file:/home/gabriel/.m2/repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom
            file:/home/gabriel/.m2/repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.jar
            file:/home/gabriel/Development/android-sdk-linux/extras/android/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom
            file:/home/gabriel/Development/android-sdk-linux/extras/android/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.jar
            file:/home/gabriel/Development/android-sdk-linux/extras/google/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom
            file:/home/gabriel/Development/android-sdk-linux/extras/google/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.jar
        Required by:
            SistarjsMobile:react-native-dialogs:unspecified



```

**Comment by kkgelu** [comment]
Same here.... on RN0.21

**Comment by lsps9150414** [comment]
same on RN0.21

**Comment by aakashns** [comment]
Hey guys, sorry about the issue. I'm on vacation right now, so can't look into it properly. I might be able to try and fix it next week.
Can you try older versions of the library and see if it works?

**Comment by Thomas101** [comment]
I don't know if this will help anyone, but I had a similar issue with another library. I'm pretty sure it was the same error. It's because you don't have the latest google play api installed on your machine. Here's what I did to resolve it...

1.) Open android studio
2.) Go configure > SDK Manager
3.) Open SDK tools tab
4.) Ensure you have version 24.4.1 of Android SDK Tools installed so that it looks like below...
![unnamed](https://cloud.githubusercontent.com/assets/103586/13964627/82774af4-f062-11e5-9609-b0a7d952e958.png)

Hope it helps someone!

**Comment by Pocket-titan** [comment]
I tried all older versions, none worked. The logs all look the same: 

```
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:appcompat-v7:23.1.
     Searched in the following locations:
         https://jitpack.io/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom
         https://jitpack.io/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.jar
         file:/android/extras/android/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom
         file:/android/extras/android/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.jar
         file:/android/extras/google/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom
         file:/android/extras/google/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.jar
     Required by:
         com.github.aakashns:android:c9fa094d8a
   > Could not find any version that matches com.facebook.react:react-native:0.14.+.
     Searched in the following locations:
         https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml
         https://jitpack.io/com/facebook/react/react-native/
         file:/android/extras/android/m2repository/com/facebook/react/react-native/maven-metadata.xml
         file:/android/extras/android/m2repository/com/facebook/react/react-native/
         file:/android/extras/google/m2repository/com/facebook/react/react-native/maven-metadata.xml
         file:/android/extras/google/m2repository/com/facebook/react/react-native/
     Required by:
         com.github.aakashns:android:c9fa094d8a
   > Could not find com.github.afollestad.material-dialogs:core:0.8.5.0.
     Searched in the following locations:
         https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
         https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
         file:/android/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
         file:/android/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
         file:/android/extras/google/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
         file:/android/extras/google/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
     Required by:
         com.github.aakashns:android:c9fa094d8a
```

When I visit the Jitpack urls it's trying to search, I get a blank screen and the console logs a 404 error.
Could this be a problem on Jitpacks end?

**Comment by locly** [comment]
@Pocket-titan, as before not related to this lib, similar issue with another, but might help....

Mine was also looking on my local machine for the libs... e.g. in
`file:/Users/tom/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom`

How have you set your local android path for react native? If you've used the bash variable so far, try creating the `$project_dir/android/local.properties` and adding you path into there...

```
sdk.dir=/Users/tom/Library/Android/sdk/
```

**Comment by Thomas101** [comment]
@Pocket-titan, as before not related to this lib, similar issue with another, but might help....

Mine was also looking on my local machine for the libs... e.g. in
`file:/Users/tom/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1/appcompat-v7-23.1.pom`

How have you set your local android path for react native? If you've used the bash variable so far, try creating the `$project_dir/android/local.properties` and adding you path into there...

```
sdk.dir=/Users/tom/Library/Android/sdk/
```

**Comment by texas697** [comment]
same issue. really want to use this!

**Comment by Pocket-titan** [comment]
I've fixed the dependency issue I believe, but now my app is crashing - presumably because I'm using the newest material-dialogs, 0.8.5.7 instead of 0.8.5.0 like I believe this app uses.

I did three things. First, I followed the advice @Thomas101 gave (thanks by the way!) and set my local android path to `sdk.dir=/Users/MYUSER/Library/Android/sdk/`.

Then, I saw in `android/app/build.gradle` that it was searching for `appcompat-v7:23.1`, but there doesn't appear to be a version `23.1`, only a version `23.0.1`. So I changed the appcompat version from `23.1` to `23.0.1`, and it no longer gave any errors with appcompat.

BUT, it still couldn't find the `material-dialogs/core` stuff. I saw that it was searching for version `0.8.5.0`, while on Jitpack I could only find `0.8.5.3` up until `0.8.5.7`. So, I changed the material-dialogs version to `0.8.5.7` and the dependencies resolved just fine. 
But it's not working because I don't think this library is using the newest version of material-dialogs yet

So it looks like Jitpack only hosts the latest 5 versions? I could request all of the versions listed there, but not version `0.8.5.0`. If so, then updating to `material-dialogs@0.8.5.7` should fix it.

**Comment by Pocket-titan** [comment]
@aakashns The open pull request fixes this, you might want to take a look at it

**Comment by aakashns** [comment]
@Pocket-titan Thanks for pointing this out. I have merged the pull request and tested it on my end, and it seems to be woking fine with react-native 0.22.

**Comment by vonovak** [comment]
closing since the issue seems to be fixed.
